xapi:
  baseUrl: https://xapi.us/api
  apiToken: Bearer ${API_TOKEN}
tg:
  baseUrl: https://api.telegram.org/bot
  apiToken: ${TGAPI_TOKEN}
  botName: Asha E-Bot
  systemCaller: Asha Sharma
  systemArg: Power your dreams
ebot:
  serviceHost: ${SERVICE_HOST}
  limitPerUser: 5
  requestsPerMin: 10.0
clown:
  csvUrl: https://wokedetector.cirnoslab.me/data.csv
server:
  servlet:
    context-path: /
spring:
  ai:
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        options:
          model: "gpt-4o"
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DB}
    username: ${PG_USER}
    password: ${PG_PASS}
  flyway:
    baseline-on-migrate: true
    baseline-version: 11
  jpa:
    hibernate:
      ddl-auto: none
messages:
  periodical:
    text: Пацаны, %s прекрасно шарит! Как и все в этом чате!
    probability: 5
  congrats: Разъебывает
  congrats_sticker: CAACAgIAAxkBAAMGZce_ogbN5DbsntxkIyOJ3RTKFZ8AAsEXAAIdTRFKqcvbjvNhzeU0BA
  congrats_emoji: 😐
  scream_gif: CgACAgIAAx0CefUPJwACAo9n5Y6vw7IM0GBS8jp8efYYcQqqFAAClwEAAvwlgEqBXgu126okjjYE
  scream_sets: adVanced2,adVanced
  deactivate: Пиздец, %s ливнул из чата, нахуя нам его ачивки? Выключим пока...
  activate: С возвращением, %s! Включил вывод твоих ачивок, с тебя $20.
  react:
    clown:
      emoji: 🤡
      triggers: русня,русне,русней,руснёй,русню,хохол,хохлы,хохлов,хохлам,хохла,хохлу,хохло,я люблю рэп,пидорах
      sticker:
        id: CAACAgIAAx0CefUPJwACAqpolIdtj4VhU2yYInAGYdc2BsZ7WAAC6H8AAuKbkUjqoUrVN5dgrDYE
        uniqueId: AgAD6H8AAuKbkUg
        stickerSet: drochil_quotes
    custom:
      man:
        sticker: CAACAgIAAx0CefUPJwACATlmK6pvk0ytO4lGPEVVriEQOmdK3QACkhAAAqtKyUuSgBNYR-8rQDQE
        emojiId: 5456480998646620452
        emoji: 👨‍🦰
        triggers: голубой,гей,мужчина,мужской,мужское,мужское,мужская,гея
        exceptions: гейм,гейб,адыге,гейл,гейн,гейш,гейз,эге,гейт,гейпас,геймпас,сергей